flo-check-homework-decorate-games: new --no-exec-check option
* flo-check-homework-decorate-games: new option (--no-exec-check or -X)
to skip the executable check in generated wrapper scripts. This can be
useful in setups where the user running the wrapper script normally
doesn't have the permissions to execute the desired program, but gains
them through the optional program launcher (cf. previous commit).

diff --git a/tools/flo-check-homework-decorate-games/flo-check-homework-decorate-games b/tools/flo-check-homework-decorate-games/flo-check-homework-decorate-games
--- a/tools/flo-check-homework-decorate-games/flo-check-homework-decorate-games
+++ b/tools/flo-check-homework-decorate-games/flo-check-homework-decorate-games
@@ -55,22 +55,32 @@ def create_wrappers(data_file):
                 pretty_name, name, display_cmd))
         fch_env_str   = "LANG={} ".format(params.fch_locale)
         child_env_str = "LANG={} ".format(params.prog_locale)
+        command = '{fch_env_str}flo-check-homework -p "{pretty_name}" -- ' \
+            '/usr/bin/env {child_env_str}"$@"'.format(
+            pretty_name=pretty_name,
+            fch_env_str=fch_env_str,
+            child_env_str=child_env_str)
+
+        # Main part of the wrapper script
+        if params.exec_check:
+            main = """\
+cmd="$1"
+
+if [ -x "$cmd" ]; then
+    {0}
+else
+    echo "'$cmd' is not executable. Aborting." >&2
+    exit 1
+fi""".format(command)
+        else:
+            main = command
+
+        # Contents of the wrapper script
         contents = """\
 #! /bin/sh
 
 set -- {cmdline} "$@"
-cmd="$1"
-
-if [ -x "$cmd" ]; then
-    {fch_env_str}flo-check-homework -p "{pretty_name}" -- /usr/bin/env {child_env_str}"$@"
-else
-    echo "'$cmd' is not executable. Aborting." >&2
-    exit 1
-fi\n""".format(pretty_name=pretty_name,
-               cmdline=cmdline,
-               fch_env_str=fch_env_str,
-               child_env_str=child_env_str)
-
+{main}\n""".format(cmdline=cmdline, main=main)
         mode = 0
         for attr in ("RUSR", "WUSR", "XUSR", "RGRP", "XGRP", "ROTH", "XOTH"):
             mode |= getattr(stat, "S_I" + attr)
@@ -148,6 +158,11 @@ if COMMAND is empty.""".format(
       value of the LANG environment variable used for running
       the target programs ("games") in the wrapper scripts
       (default: %(default)s)"""),
+    parser.add_argument('-X', '--no-exec-check', dest='exec_check',
+                        action='store_false', help="""\
+      don't check the executable bit of the desired program in wrapper
+      scripts, just launch flo-check-homework with the appropriate
+      arguments""")
     parser.add_argument('--help', action="help",
                         help="display this message and exit")
 
